# Assignment teesting workflow config for CI/CD on Github

name: Data Packer Tests

# Controls when the action will run. 
on:
  # Triggers the workflow for main branch on git push
  push:
    branches: [main]
  # Triggers workflow for or any branch on pull requests
  pull_request:
    branches:
      - '**'
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow is defined of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run_spec"
  run_spec:
    strategy:
      # don't cancel other jobs if one fails
      fail-fast: false
      # maximum number of jobs that can run simultaneously
      max-parallel: 1
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest  # Runs on latest builds of matrix OSes
    env:
      BUNDLE_WITHOUT: production # skip installing production gem (pg)
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
    
      # Builds on a predefined action that has Ruby installed 
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run all specs
        run: |
          bundle exec ruby packer_spec.rb 